Admin_panel/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('SampleApp.urls')),
]

SampleApp/urls.py
"""Defines url patterns for SampleApp."""

from django.urls import path
from . import views


app_name = 'SampleApp'
urlpatterns = [
    #Home page.
    path('', views.index, name='index'),
    
    #Show all sample objects.
    path('sampleObjects/', views.sampleObjects, name='sampleObjects'),
    
    #Detail page for a single object.
    path('sampleObjects/<int:sampleObject_id>/', views.sampleObject, 
    name='sampleObject'),

    #Page for adding a new sampleObject.
    path('new_sampleObject/', views.new_sampleObject, name='new_sampleObject'),

    #Page for adding a new entry.
    path('new_entry/<int:sampleObject_id>/', views.new_entry, name='new_entry'),

    #Page for editing an entry.
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
 
]

users/urls.py
"""Defines url patterns for users."""

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'
urlpatterns = [
    #Login page.
    path('login/', 
    auth_views.LoginView.as_view(template_name='users/login.html'), 
    name='login'),

    #Logout page.
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    #Registration page.
    path('register/', views.register, name='register'),

]

SampleApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class SampleModel(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.text

class Entry(models.Model):
    sampleObject = models.ForeignKey('SampleModel', on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'entries'
        
    def __str__(self):
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

SampleApp/forms.py
from django import forms

from .models import SampleModel, Entry


class SampleModelForm(forms.ModelForm):
    class Meta:
        model = SampleModel
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

SampleApp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import SampleModel, Entry
from .forms import SampleModelForm, EntryForm

# Create your views here.
def index(request):
    """SampleApp home page"""
    return render(request, 'SampleApp/index.html')

@login_required
def sampleObjects(request):
    sampleObjects = SampleModel.objects.filter(owner=request.user).order_by('date_added')
    context = {'sampleObjects': sampleObjects}
    return render(request, 'SampleApp/sampleObjects.html', context)

@login_required
def sampleObject(request, sampleObject_id):
    sampleObject = SampleModel.objects.get(id=sampleObject_id)
    if sampleObject.owner != request.user:
        raise Http404
    entries = sampleObject.entry_set.order_by('-date_added')
    context = {'sampleObject': sampleObject, 'entries': entries}
    return render(request, 'SampleApp/sampleObject.html', context)

@login_required
def new_sampleObject(request):
    if request.method != "POST":
        form = SampleModelForm()
    else:
        form = SampleModelForm(request.POST)
        if form.is_valid():
            new_sampleObject = form.save(commit=False)
            new_sampleObject.owner = request.user
            new_sampleObject.save()
            return HttpResponseRedirect(reverse('SampleApp:sampleObjects'))
            
    context = {'form': form}
    return render(request, 'SampleApp/new_sampleObject.html', context)

@login_required
def new_entry(request, sampleObject_id):
    sampleObject = SampleModel.objects.get(id=sampleObject_id)
    
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.sampleObject = sampleObject
            new_entry.save()
            return HttpResponseRedirect(reverse('SampleApp:sampleObject',
            args=[sampleObject_id]))
            
    context = {'sampleObject': sampleObject, 'form': form}
    return render(request, 'SampleApp/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    sampleObject = entry.sampleObject
    if sampleObject.owner != request.user:
        raise Http404
    if request.method != "POST":
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('SampleApp:sampleObject', 
            args=[sampleObject.id]))
            
    context = {'entry': entry,'sampleObject': sampleObject, 'form': form}
    return render(request, 'SampleApp/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, authenticate 
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
    if request.method != "POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('SampleApp:index'))
            
    context = {'form': form}
    return render(request, 'users/register.html', context)

SampleApp/templates/SampleApp/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="pl"></html>
    <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      
      <title>Home</title>
      
      {% bootstrap_css %}
      {% bootstrap_javascript %}
         
    </head>

<body>

  <!--Statyczny pasek nawigacji.-->
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#navbar"
            aria-expanded="false" aria-controls="navbar">
        </button>
        <a class="navbar-brand" href="{% url 'SampleApp:index' %}">
          Home</a>
      </div>
      
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'SampleApp:sampleObjects' %}">Objects</a></li>
        </ul>
        
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><a>Hello, {{ user.username }}.</a></li>
            <li><a href="{% url 'users:logout' %}">Log out</a></li>
          {% else %}
            <li><a href="{% url 'users:register' %}">Register</a></li>
            <li><a href="{% url 'users:login' %}">Sign in</a></li>
          {% endif %}
        </ul>
      </div><!--/.nav-collapse -->
    
    </div>
  </nav>
  
  <div class="container">
  
    <div class="page-header">
      {% block header %}{% endblock header %}
    </div>  
    <div>
      {% block content %}{% endblock content %}
    </div>
    
  </div><!-- /container -->

</body>
</html>

SampleApp/templates/SampleApp/edit_entry.html
{% extends "SampleApp/base.html" %}

{% block content %}

  <p><a href="{% url 'SampleApp:sampleObject' sampleObject.id %}"> 
      {{ sampleObject }}</a></p>
  <p>Edit entry:</p>

  <form action="{% url 'SampleApp:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save</button>
  </form>

{% endblock content %}

SampleApp/templates/SampleApp/index.html
{% extends "SampleApp/base.html" %}

  {% block header %}
    <div class='jumbotron'>
    <center>
      <h1>The simple web application created in Django.</h1>
    </center>
    </div>
  {% endblock header %}

{% block content %}
{% endblock content %}

SampleApp/templates/SampleApp/new_entry.html
{% extends "SampleApp/base.html" %}

{% block content %}

  <p><a href="{% url 'SampleApp:sampleObject' sampleObject.id %}"> 
      {{ sampleObject }}</a></p>
  <p>Add new entry:</p>

  <form action="{% url 'SampleApp:new_entry' sampleObject.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add entry</button>
  </form>

{% endblock content %}

SampleApp/templates/SampleApp/new_sampleObject.html
{% extends "SampleApp/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h3>Add a new object:</h3>
{% endblock header %}

{% block content %}
  <form action="{% url 'SampleApp:new_sampleObject' %}" method='post' 
  class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    
  {% buttons %}
    <button name="submit" class="btn btn-primary">Add object</button>
  {% endbuttons %}
  </form>

{% endblock content %}

SampleApp/templates/SampleApp/sampleObject.html
{% extends "SampleApp/base.html" %}

{% block header %}
  <h3>{{ sampleObject }}</h3>
{% endblock header %}

{% block content %}
  <p>
    <a href="{% url 'SampleApp:new_entry' sampleObject.id %}">Add new entry</a>
  </p>

  {% for entry in entries %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4>
          {{ entry.date_added|date:'d M Y H:i' }}
          <small>
            <a href="{% url 'SampleApp:edit_entry' entry.id %}">Edit entry</a>
          </small>
        </h4>
      </div>
      <div class="panel-body">
        {{ entry.text|linebreaks }}
      </div>
    </div><!-- panel -->
  {% empty %}
      No entry.
  {% endfor %}


{% endblock content %}

SampleApp/templates/SampleApp/sampleObjects.html
{% extends "SampleApp/base.html" %}

{% block header %}
  <h3>Objects:</h3>
{% endblock header %}
{% block content %}

  <ul>
    {% for sampleObject in sampleObjects %}
      <li>
        <h4>
          <a href="{% url 'SampleApp:sampleObject' sampleObject.id %}">
              {{ sampleObject }}</a>
        </h4>
      </li>
    {% empty %}
      <li>No objects</li>
    {% endfor %}
  </ul>
  
  <u>
    <h4><a href="{% url 'SampleApp:new_sampleObject' %}">
        Add a new object</a></h4>
  </u>
{% endblock content %}

users/templates/users/login.html
{% extends "SampleApp/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Sign in to your account</h2>
{% endblock header %}

{% block content %}

  <form method="post" action="{% url 'users:login' %}" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  
  {% buttons %}
    <button name="submit" class="btn btn-primary">Sign in</button>
  {% endbuttons %}
  
  
  <input type="hidden" name="next" value="{% url 'SampleApp:index' %}" />
  </form>

{% endblock content %}

users/templates/users/register.html
{% extends "SampleApp/base.html" %}

{% block content %}

  <form method="post" action="{% url 'users:register'%}">
    {% csrf_token %}
    {{ form.as_p }}
    
    <button name="submit">Sign up</button>
    <input type="hidden" name="next" value="{% url 'SampleApp:index' %}" />
    </form>

{% endblock content %}